hcbresourcesite/hcbcapacity/urls.py
from django.urls import path
from django.contrib import admin

from . import views

app_name = 'hcbcapacity'

urlpatterns = [
   
    path('', views.index, name='index'),
    path('update-api-table/', views.update_api_table, name='update-api-table' ),
    path('pie-chart/', views.pie_chart, name='pie-chart'),
    path('proj-wo-da/', views.proj_without_da, name='project-wo-da'),
    path('<int:prod_id>/', views.daProjects, name='da-projects'),
    path('enter-info/', views.enter_info,name='enter-info'),
   
]

hcbresourcesite/hcbresourcesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('hcbcapacity.urls')),
    
    
]

hcbresourcesite/hcbcapacity/forms.py
from django.forms import ModelForm, TextInput, Select, DateInput, NumberInput, HiddenInput, CharField, DateField,forms
from django import forms
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from .models import api_proj_list
import random
from datetime import date, datetime

class UpdateApiProjectList(ModelForm):        
      
      class Meta:
      
          PROJ_TYPE = [('Managed EES / Pulse License / Pulse License + Additional Services' , 'Managed EES / Pulse License / Pulse License + Additional Services'),('Traditional Survey (Confirmit, TRO, CAT,TRP)','Traditional Survey (Confirmit, TRO, CAT, TRP)'),('None','None')]
      
          CONT_TYPE = [('2b. License + support (incl. support for a managed project)','2b. License + support (incl. support for a managed project)'),('3. Managed projects on EES','3. Managed projects on EES'),('None','None')]

          SUB_REG = [('Asia Pacific', 'Asia Pacific'),('CEMEA', 'CEMEA'),('North America', 'North America'), ('Western Europe', 'Western Europe'), ('Great Britain', 'Great Britain')]

          DEL_ANA = [('None','None'),('Yang Xu','Yang Xu'), ('Waldy Capule','Waldy Capule'), ('Ronald Macalipay','Ronald Macalipay'), ('Maricar Garzon','Maricar Garzon'), ('Louie John Diaz','Louie John Diaz'), ('Leslie Aubrey Igaharas','Leslie Aubrey Igaharas'), ('Khumille Lopez','Khumille Lopez'), ('Justine Carmel Tayag','Justine Carmel Tayag'), ('Joy Angelie Baltazar','Joy Angelie Baltazar'), ('Joey Alvarado','Joey Alvarado'),('Joel Juatchon','Joel Juatchon'), ('Finella Francesca Panganiban','Finella Francesca Panganiban'), ('Eileen Faye Placido','Eileen Faye Placido') ,('Diana Asis','Diana Asis'),  ('Wilbur Dionglay','Wilbur Dionglay'), ('Jui Hsia Liu','Jui Hsia Liu'), ('Shara Dyan Escobido','Shara Dyan Escobido'), ('Jasmine Jake Halili','Jasmine Jake Halili'), ('Sharisse Perez','Sharisse Perez'), ('James Domogma','James Domogma'), ('John Mer Giray','John Mer Giray')]

          model = api_proj_list

          fields = ['project_key','project_type','sub_region', 'contract_type','summary','created','proj_status','survey_setup_start_date','admin_start','admin_end','ees_start_date','ees_submission_end_date','ees_first_results_release_date','delivery_analyst','da_hours']
          
          widgets = {
              
              'project_key' : HiddenInput(),
              'project_type' : Select(attrs={'class':'form-control'}, choices=PROJ_TYPE),
              'contract_type': Select(attrs={'class' : 'form-control'}, choices=CONT_TYPE),
              'sub_region': Select(attrs={'class' : 'form-control'}, choices=SUB_REG),
              'proj_status': HiddenInput(attrs={'value' : 'Preparation'}),
              'summary': TextInput(attrs={'class' : 'form-control', 'required': True}),
              'created': DateInput(format='%Y-%m-%d',attrs={'class' : 'form-control', 'value':datetime.now()}),
              'survey_setup_start_date': DateInput(format='%Y-%m-%d',attrs={'class' : 'form-control','required' : True}),                   
              'admin_start' : DateInput(format='%Y-%m-%d',attrs={'class' : 'form-control','required' : True}),               
              'admin_end' : DateInput(format='%Y-%m-%d',attrs={'class' : 'form-control','required' : True}),
              'ees_start_date': DateInput(format='%Y-%m-%d',attrs={'class' : 'form-control','required' : True}),
              'ees_submission_end_date': DateInput(format='%Y-%m-%d',attrs={'class' : 'form-control', ' required' : True}),
              'ees_first_results_release_date' : DateInput(format='%Y-%m-%d',attrs={'class' : 'form-control', 'required' : True}),                 
              'delivery_analyst' : Select(attrs={'class' : 'form-control', 'required' : True}, choices=DEL_ANA),              
              'da_hours' : NumberInput(attrs={'class':'form-control', 'required' : True})           
              

          }
        
          error_messages = {
             'summary' : {'required': 'Please enter the name of the project.'}
          }
            
          
          
          

       


      

          
              

          

hcbresourcesite/hcbcapacity/views.py
from os import error, terminal_size
from django.db.models.aggregates import Avg
from django.db.models.expressions import F, Subquery
from django.db.models.fields import IntegerField
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.db.models import Sum, Count, Q, FloatField
from django.http import HttpResponse, HttpResponseRedirect
from .models import api_proj_list, summaryTable, std_hours, daProdByMonth, daAverageProd
from django.template import loader
from django.core.exceptions import ValidationError
from .forms import UpdateApiProjectList
from .preprocess import forecastTblPreProcess
from .dbsave import dbStore
from .dproc import dProcess
from jira import JIRA, JIRAError
from collections import OrderedDict
import random
from  datetime  import datetime as dt, timedelta
import json
import psycopg2

# Create your views here.
def index(request):
    latest_project_list = api_proj_list.objects.exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold')).order_by('admin_start')
    
    print(type(latest_project_list))
    
    context = {
        'latest_project_list' : latest_project_list,
    }
    
    return render(request,'hcbcapacity/index.html', context)

def pie_chart(request):
    
    print("This is a request.", request)    

    if request.method == 'GET':
       projyr = request.GET["project_yr"]
       daProd = daProdByMonth.objects.filter(project_year__exact = projyr)
   
       
    print("This is the daprod", daProd)
  
    #for pie chart.
    labels_pie = []
    data_pie = []

    #for projstat data.
    labels_stat_pie = []
    data_stat_pie = []

    #for bar chart
    labels_bar = []
    data_bar = []

    #for area chart. Plotting data for the area chart.
    data_area = []

    #create queries for the specific areas in the dashboard.
    queryset_pie = api_proj_list.objects.filter(project_year__exact=projyr).values('sub_region').exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold')).annotate(da_hours=Sum('da_hours'))    

    queryset_bar = api_proj_list.objects.values('delivery_analyst').exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold')).annotate(proj_per_da=Count('project_key'))

    #Get anticipated prod percentage from the team based on the number of hours and the standard hours.
    queryset_std_hours = std_hours.objects.annotate(stdhours=(Sum('no_of_hours')*0.75)).values()
    print("These are the total hours for the year.", queryset_std_hours) 

    #query_avg_prod = daProdByMonth.objects.filter(project_year__exact=projyr).aggregate(avr_prod=((Avg(F('jan')), Avg(F('feb')), Avg(F('mar')), Avg(F('apr')), Avg(F('may')), #Avg(F('jun')), Avg(F('jul')), Avg(F('aug')), Avg(F('sep')), Avg(F('oct')), Avg(F('nov')), Avg(F('dece')))))
    
    #print('This is average prod', query_avg_prod)

    queryset_area_da_hours = daAverageProd.objects.filter(project_year=projyr).values()
    
    print("This is the average prod of the DAs", queryset_area_da_hours)
   

    #Create a query for the specific month

    
    query_average_jan = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(jan__exact = 0)).aggregate(jan=Avg('jan'))
    query_average_feb = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(feb__exact = 0)).aggregate(feb=Avg('feb'))
    query_average_mar = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(mar__exact = 0)).aggregate(mar=Avg('mar'))
    query_average_apr = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(apr__exact = 0)).aggregate(apr=Avg('apr'))
    query_average_may = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(may__exact = 0)).aggregate(may=Avg('may'))
    query_average_jun = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(jun__exact = 0)).aggregate(jun=Avg('jun'))
    query_average_jul = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(jul__exact = 0)).aggregate(jul=Avg('jul'))
    query_average_aug = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(aug__exact = 0)).aggregate(aug=Avg('aug'))
    query_average_sep = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(sep__exact = 0)).aggregate(sep=Avg('sep'))
    query_average_oct = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(oct__exact = 0)).aggregate(oct=Avg('oct'))
    query_average_nov = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(nov__exact = 0)).aggregate(nov=Avg('nov'))
    query_average_dec = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(dece__exact = 0)).aggregate(dece=Avg('dece'))
 
    print('This is the average for Jan', query_average_jan.get("jan"))
       

    data_area.append((query_average_jan.get("jan")))
    data_area.append((query_average_feb.get("feb")))
    data_area.append((query_average_mar.get("mar")))
    data_area.append((query_average_apr.get("apr")))
    data_area.append((query_average_may.get("may")))
    data_area.append((query_average_jun.get("jun")))
    data_area.append((query_average_jul.get("jul")))
    data_area.append((query_average_aug.get("aug")))
    data_area.append((query_average_sep.get("sep")))
    data_area.append((query_average_oct.get("oct")))
    data_area.append((query_average_nov.get("nov")))
    data_area.append((query_average_dec.get("dece")))

    data_area_final = [0 if n == None else round(n) for n in data_area ]

    print('This is the consolidated data_area', data_area)
    months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

    
    #This is for the project counts by DA.
    project_count = api_proj_list.objects.exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold')).aggregate(proj_count=Count('project_key'))
    
    #count of projects based on project status.
    proj_stat = api_proj_list.objects.filter(project_year__exact=projyr).values('proj_status').annotate(proj_count=Count('proj_status'))    
    
    proj_wo_da = api_proj_list.objects.filter(Q(delivery_analyst__exact='None') & Q(project_year__exact=projyr)).exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold')).count()

    proj_w_da = api_proj_list.objects.exclude(delivery_analyst__exact='None').exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold')).count()
    
    #This is for the project status pie chart:
    for case_pie_proj_stat in proj_stat:
        for stat_key, stat_value in case_pie_proj_stat.items():
            if stat_key == 'proj_status':
                labels_stat_pie.append(stat_value)                
            else:
                data_stat_pie.append(stat_value)             


    #This is for the pie chart.
    for case_pie in queryset_pie:
        for da_key, da_value in case_pie.items():
            if da_key == 'sub_region' and da_value != None:
                labels_pie.append(da_value)                
            elif da_value != None:
                data_pie.append(da_value)
    
    #This is for the bar chart.
    for case_bar in queryset_area_da_hours:
        for da_key, da_value in case_bar.items():
            if da_key == 'delivery_analyst' and da_value != None:
                labels_bar.append(da_value)                
            elif da_key == 'average_prod':
                data_bar.append(round(da_value))



    context = {
        'labels_pie' : labels_pie,
        'data_pie' : data_pie,
        'labels_stat_pie': labels_stat_pie,
        'data_stat_pie':data_stat_pie,
        'labels_bar': labels_bar,
        'data_bar' : data_bar,
        'labels_area': months,
        'data_area' : data_area_final,
        'proj_count' : project_count['proj_count'],
        'proj_wo_da' : proj_wo_da,
        'proj_w_da' : proj_w_da,
        'daProd' : daProd,
    }

    return render(request, 'hcbcapacity/pie_chart.html', context)

def proj_without_da(request):

   
    list_projects_wo_da = api_proj_list.objects.filter(delivery_analyst__exact='None').exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold') | 
    Q(complexity__exact='2b. License + support for managed project (Lite/Base + Premium)')).order_by('admin_start')

    
    context = {
        'list_projects_wo_da' : list_projects_wo_da,
    }

    return render(request, 'hcbcapacity/projwoda.html', context)


def daProjects(request, prod_id):

    if request.method == 'GET':
        da_prod = daProdByMonth.objects.filter(prod_id__exact=prod_id).values('delivery_analyst')
       
        dafilter = da_prod[0]['delivery_analyst']
        print(dafilter)      

    list_projects_w_da = api_proj_list.objects.filter(delivery_analyst__contains=dafilter).order_by('admin_start')
   
    context = {
        'list_projects_w_da' : list_projects_w_da,
    }

    return render(request,'hcbcapacity/projwda.html', context)


def enter_info(request):
    
    #first, create and initiate a form instance of the API project.
    #form = UpdateApiProjectList()

    #Generate a project key for from the entry form.
    forkey_gen = (random.random()*1000)
    forkey = int(forkey_gen)
    x=(f'A1-{forkey}')
    
    preProc = forecastTblPreProcess()
    dbStorer = dbStore()

    if request.method == 'POST':
       
        # this is used to check if the request.POST is indeed passing off work in the post
        #print('This is the POST:', request.POST)
        
        #pass on the POST request back to the initialized form. 
        form = UpdateApiProjectList(request.POST)        #print('this is the type of form:', type(form))

        print('This is the summary value', form['summary'].value())
        
        # Create a form instance and populate it with data from the request (binding):
        if form.is_valid():
            
            form.save()        
            project_key = form['project_key'].value()

hcbresourcesite/hcbcapacity/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - EI Software Delivery Resourcing</title>
        <link href="{% static 'hcbcapacity/dist/css/styles.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">    
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        
    </head>
    <body class="sb-nav-fixed">
        
        <nav class="sb-topnav navbar navbar-expand navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'hcbcapacity:index' %}"><img src="http://uxstandards.willistowerswatson.com/wp-content/themes/wtw-UX-Standards/assets/img/willistowerswatson-logo.svg" width="210" alt="Willis Towers Watson"></a>
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
            
          
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" action="{% url 'hcbcapacity:update-api-table' %}" method="POST">
                {%csrf_token%}
                <button class="btn btn-primary" id="submit" type="submit" value="submit" >Refresh Database</button>
            </form>
        </nav>
        
       
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>                           
                           
                            <a class="nav-link" href="{% url 'hcbcapacity:pie-chart' %}?project_yr=2022">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Dashboard
                            </a>
                            
                            <div class="sb-sidenav-menu-heading">Addons</div>
                            <a class="nav-link" href="{% url 'hcbcapacity:index' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Project List
                            </a>
                            <a class="nav-link" href="{% url 'hcbcapacity:enter-info' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Pipeline
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Capacity Site:</div>
                        Check Associate resource capacity
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    {%block content %}
                    if this shows, I am eff'd up! :D
                    {% endblock content %}                      
                   
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; HCB Manila resource site {% now "Y" %}</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
       
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>       
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'hcbcapacity/dist/js/scripts.js'%}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        
        
       
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'hcbcapacity/dist/assets/demo/datatables-demo.js'%}"></script>
    </body>
</html>