hcbresourcesite/hcbcapacity/urls.py
from django.urls import path
from django.contrib import admin

from . import views

app_name = 'hcbcapacity'

urlpatterns = [
   
    path('', views.index, name='index'),
    path('update-api-table/', views.update_api_table, name='update-api-table' ),
    path('pie-chart/', views.pie_chart, name='pie-chart'),
    path('proj-wo-da/', views.proj_without_da, name='project-wo-da'),
    path('<int:prod_id>/', views.daProjects, name='da-projects'),
    path('enter-info/', views.enter_info,name='enter-info'),
   
]

hcbresourcesite/hcbresourcesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', include('hcbcapacity.urls')),
    
    
]

hcbresourcesite/hcbcapacity/models.py
from os import truncate
from django.db import models
from django.core.exceptions import ValidationError
from django.db.models import manager
from django.utils.translation import gettext_lazy as _

# Create your models here.

class api_proj_list(models.Model):
      
      project_key = models.CharField(primary_key=True, max_length=80)
      project_type = models.CharField(blank=True,null=True,max_length=255)
      contract_type = models.CharField(blank=True,null=True,max_length=100)
      summary = models.TextField(blank=True,null=True)      
      sub_region = models.TextField(blank=True,null=True)
      proj_status = models.TextField(blank=True,null=True)
      complexity = models.TextField(blank=True,null=True)
      delivery_analyst = models.TextField(blank=True,null=True)
      configuration_analyst = models.TextField(blank=True,null=True)
      production_analyst = models.TextField(blank=True,null=True)
      created = models.DateTimeField(blank=True,null=True)
      hierarchy_setup_start_date = models.DateTimeField(blank=True,null=True)
      hierarchy_setup_end_date = models.DateTimeField(blank=True,null=True)
      survey_setup_start_date = models.DateTimeField(blank=True,null=True)
      survey_setup_submission_CSD = models.DateTimeField(blank=True,null=True)
      tech_prestest_start_date = models.DateTimeField(blank=True,null=True)
      tech_pretest_end_date = models.DateTimeField(blank=True,null=True)
      survey_lockdown_start_date = models.DateTimeField(blank=True,null=True)
      survey_lockdown_end_date = models.DateTimeField(blank=True,null=True)
      admin_start = models.DateTimeField(blank=True,null=True)
      admin_end = models.DateTimeField(blank=True,null=True)
      mdb_setup_start = models.DateTimeField(blank=True,null=True)
      mdb_submission_date = models.DateTimeField(blank=True,null=True)
      ees_start_date = models.DateTimeField(blank=True,null=True)
      ees_submission_end_date = models.DateTimeField(blank=True,null=True)
      ees_first_results_release_date = models.DateTimeField(blank=True,null=True)
      ees_second_results_release_date = models.DateTimeField(blank=True,null=True)
      da_hours = models.FloatField(blank=True, null=True)
      ca_hours = models.FloatField(blank=True, null=True)
      pa_hours = models.FloatField(blank=True, null=True)
      project_year = models.IntegerField(blank=True, null=True)
      month = models.CharField(blank=True, null=True,max_length=30)
      standard_hours = models.FloatField(blank=True, null=True)
      
      # def save(self, *args, **kwargs):
      #       if self.admin_start:
      #             self.month = self.admin_start.strftime("%B")
      #       super(api_proj_list, self).save(*args,**kwargs)

      def __str__(self):
            return self.summary
     
      


class summaryTable(models.Model):
      project_key_forecast = models.ForeignKey(api_proj_list, on_delete=models.CASCADE, null= True)
      delivery_analyst = models.TextField(null=True,blank=True)
      project_year= models.IntegerField(null=True,blank=True)      
      sub_region = models.TextField(blank=True,null=True)
      jan = models.FloatField(null=True,blank=True)
      feb = models.FloatField(null=True,blank=True)
      mar = models.FloatField(null=True,blank=True)
      apr = models.FloatField(null=True, blank=True)
      may = models.FloatField(null=True,blank=True)
      jun = models.FloatField(null=True,blank=True)
      jul = models.FloatField(null=True, blank=True)
      aug = models.FloatField(null=True,blank=True)
      sep = models.FloatField(null=True,blank=True)
      oct = models.FloatField(null=True,blank=True)
      nov = models.FloatField(null=True,blank=True)
      dec = models.FloatField(null=True,blank=True)
      

class std_hours(models.Model):
      month_nm = models.TextField(null=False,blank=False)
      yr = models.IntegerField(null=False,blank=False)
      no_of_hours = models.FloatField(null=False,blank=False)


class da_list(models.Model):
      da_name = models.TextField(null=False, blank=False)
      region = models.TextField(null=False, blank=False)

class daProdByMonth(models.Model):
      prod_id = models.IntegerField(primary_key=True)
      delivery_analyst = models.CharField(max_length=100)
      sub_region = models.TextField()
      project_year = models.IntegerField()
      jan = models.FloatField()
      feb = models.FloatField()
      mar = models.FloatField()
      apr = models.FloatField()
      may = models.FloatField()
      jun = models.FloatField()
      jul = models.FloatField()
      aug = models.FloatField()
      sep = models.FloatField()
      oct = models.FloatField()
      nov = models.FloatField()
      dece = models.FloatField()
      class Meta:
            db_table = u'da_prod_by_month'
            managed = False

class daAverageProd(models.Model):
      prod_id = models.IntegerField(primary_key=True)
      delivery_analyst = models.CharField(max_length=100)
      project_year = models.IntegerField()
      average_prod = models.FloatField()
      class Meta:
            db_table=u'da_average_prod'
            managed = False

hcbresourcesite/hcbcapacity/views.py
from os import error, terminal_size
from django.db.models.aggregates import Avg
from django.db.models.expressions import F, Subquery
from django.db.models.fields import IntegerField
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.db.models import Sum, Count, Q, FloatField
from django.http import HttpResponse, HttpResponseRedirect
from .models import api_proj_list, summaryTable, std_hours, daProdByMonth, daAverageProd
from django.template import loader
from django.core.exceptions import ValidationError
from .forms import UpdateApiProjectList
from .preprocess import forecastTblPreProcess
from .dbsave import dbStore
from .dproc import dProcess
from jira import JIRA, JIRAError
from collections import OrderedDict
import random
from  datetime  import datetime as dt, timedelta
import json
import psycopg2

# Create your views here.
def index(request):
    latest_project_list = api_proj_list.objects.exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold')).order_by('admin_start')
    
    print(type(latest_project_list))
    
    context = {
        'latest_project_list' : latest_project_list,
    }
    
    return render(request,'hcbcapacity/index.html', context)

def pie_chart(request):
    
    print("This is a request.", request)    

    if request.method == 'GET':
       projyr = request.GET["project_yr"]
       daProd = daProdByMonth.objects.filter(project_year__exact = projyr)
   
       
    print("This is the daprod", daProd)
  
    #for pie chart.
    labels_pie = []
    data_pie = []

    #for projstat data.
    labels_stat_pie = []
    data_stat_pie = []

    #for bar chart
    labels_bar = []
    data_bar = []

    #for area chart. Plotting data for the area chart.
    data_area = []

    #create queries for the specific areas in the dashboard.
    queryset_pie = api_proj_list.objects.filter(project_year__exact=projyr).values('sub_region').exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold')).annotate(da_hours=Sum('da_hours'))    

    queryset_bar = api_proj_list.objects.values('delivery_analyst').exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold')).annotate(proj_per_da=Count('project_key'))

    #Get anticipated prod percentage from the team based on the number of hours and the standard hours.
    queryset_std_hours = std_hours.objects.annotate(stdhours=(Sum('no_of_hours')*0.75)).values()
    print("These are the total hours for the year.", queryset_std_hours) 

    #query_avg_prod = daProdByMonth.objects.filter(project_year__exact=projyr).aggregate(avr_prod=((Avg(F('jan')), Avg(F('feb')), Avg(F('mar')), Avg(F('apr')), Avg(F('may')), #Avg(F('jun')), Avg(F('jul')), Avg(F('aug')), Avg(F('sep')), Avg(F('oct')), Avg(F('nov')), Avg(F('dece')))))
    
    #print('This is average prod', query_avg_prod)

    queryset_area_da_hours = daAverageProd.objects.filter(project_year=projyr).values()
    
    print("This is the average prod of the DAs", queryset_area_da_hours)
   

    #Create a query for the specific month

    
    query_average_jan = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(jan__exact = 0)).aggregate(jan=Avg('jan'))
    query_average_feb = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(feb__exact = 0)).aggregate(feb=Avg('feb'))
    query_average_mar = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(mar__exact = 0)).aggregate(mar=Avg('mar'))
    query_average_apr = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(apr__exact = 0)).aggregate(apr=Avg('apr'))
    query_average_may = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(may__exact = 0)).aggregate(may=Avg('may'))
    query_average_jun = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(jun__exact = 0)).aggregate(jun=Avg('jun'))
    query_average_jul = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(jul__exact = 0)).aggregate(jul=Avg('jul'))
    query_average_aug = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(aug__exact = 0)).aggregate(aug=Avg('aug'))
    query_average_sep = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(sep__exact = 0)).aggregate(sep=Avg('sep'))
    query_average_oct = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(oct__exact = 0)).aggregate(oct=Avg('oct'))
    query_average_nov = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(nov__exact = 0)).aggregate(nov=Avg('nov'))
    query_average_dec = daProdByMonth.objects.filter(project_year__exact=projyr).exclude(Q(dece__exact = 0)).aggregate(dece=Avg('dece'))
 
    print('This is the average for Jan', query_average_jan.get("jan"))
       

    data_area.append((query_average_jan.get("jan")))
    data_area.append((query_average_feb.get("feb")))
    data_area.append((query_average_mar.get("mar")))
    data_area.append((query_average_apr.get("apr")))
    data_area.append((query_average_may.get("may")))
    data_area.append((query_average_jun.get("jun")))
    data_area.append((query_average_jul.get("jul")))
    data_area.append((query_average_aug.get("aug")))
    data_area.append((query_average_sep.get("sep")))
    data_area.append((query_average_oct.get("oct")))
    data_area.append((query_average_nov.get("nov")))
    data_area.append((query_average_dec.get("dece")))

    data_area_final = [0 if n == None else round(n) for n in data_area ]

    print('This is the consolidated data_area', data_area)
    months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

    
    #This is for the project counts by DA.
    project_count = api_proj_list.objects.exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold')).aggregate(proj_count=Count('project_key'))
    
    #count of projects based on project status.
    proj_stat = api_proj_list.objects.filter(project_year__exact=projyr).values('proj_status').annotate(proj_count=Count('proj_status'))    
    
    proj_wo_da = api_proj_list.objects.filter(Q(delivery_analyst__exact='None') & Q(project_year__exact=projyr)).exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold')).count()

    proj_w_da = api_proj_list.objects.exclude(delivery_analyst__exact='None').exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold')).count()
    
    #This is for the project status pie chart:
    for case_pie_proj_stat in proj_stat:
        for stat_key, stat_value in case_pie_proj_stat.items():
            if stat_key == 'proj_status':
                labels_stat_pie.append(stat_value)                
            else:
                data_stat_pie.append(stat_value)             


    #This is for the pie chart.
    for case_pie in queryset_pie:
        for da_key, da_value in case_pie.items():
            if da_key == 'sub_region' and da_value != None:
                labels_pie.append(da_value)                
            elif da_value != None:
                data_pie.append(da_value)
    
    #This is for the bar chart.
    for case_bar in queryset_area_da_hours:
        for da_key, da_value in case_bar.items():
            if da_key == 'delivery_analyst' and da_value != None:
                labels_bar.append(da_value)                
            elif da_key == 'average_prod':
                data_bar.append(round(da_value))



    context = {
        'labels_pie' : labels_pie,
        'data_pie' : data_pie,
        'labels_stat_pie': labels_stat_pie,
        'data_stat_pie':data_stat_pie,
        'labels_bar': labels_bar,
        'data_bar' : data_bar,
        'labels_area': months,
        'data_area' : data_area_final,
        'proj_count' : project_count['proj_count'],
        'proj_wo_da' : proj_wo_da,
        'proj_w_da' : proj_w_da,
        'daProd' : daProd,
    }

    return render(request, 'hcbcapacity/pie_chart.html', context)

def proj_without_da(request):

   
    list_projects_wo_da = api_proj_list.objects.filter(delivery_analyst__exact='None').exclude(Q(proj_status__exact='Completed') | Q(proj_status__exact='On Hold') | 
    Q(complexity__exact='2b. License + support for managed project (Lite/Base + Premium)')).order_by('admin_start')

    
    context = {
        'list_projects_wo_da' : list_projects_wo_da,
    }

    return render(request, 'hcbcapacity/projwoda.html', context)


def daProjects(request, prod_id):

    if request.method == 'GET':
        da_prod = daProdByMonth.objects.filter(prod_id__exact=prod_id).values('delivery_analyst')
       
        dafilter = da_prod[0]['delivery_analyst']
        print(dafilter)      

    list_projects_w_da = api_proj_list.objects.filter(delivery_analyst__contains=dafilter).order_by('admin_start')
   
    context = {
        'list_projects_w_da' : list_projects_w_da,
    }

    return render(request,'hcbcapacity/projwda.html', context)


def enter_info(request):
    
    #first, create and initiate a form instance of the API project.
    #form = UpdateApiProjectList()

    #Generate a project key for from the entry form.
    forkey_gen = (random.random()*1000)
    forkey = int(forkey_gen)
    x=(f'A1-{forkey}')
    
    preProc = forecastTblPreProcess()
    dbStorer = dbStore()

    if request.method == 'POST':
       
        # this is used to check if the request.POST is indeed passing off work in the post
        #print('This is the POST:', request.POST)
        
        #pass on the POST request back to the initialized form. 
        form = UpdateApiProjectList(request.POST)        #print('this is the type of form:', type(form))

        print('This is the summary value', form['summary'].value())
        
        # Create a form instance and populate it with data from the request (binding):
        if form.is_valid():
            
            form.save()        
            project_key = form['project_key'].value()

hcbresourcesite/hcbcapacity/templates/hcbcapacity/enterinfo.html
{%extends 'base.html' %}
{%block title%}Enter Pipeline Information{%endblock title%}
{% block nav-style %}mkt-nav{% endblock nav-style%}

{%block content%}


<div class="container-fluid">

  <h1 class="mt-4">Enter Information from Pipeline</h1>
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Dashboard</li>
  </ol>


  <div class="card mb-4">
    <div class="card-header">
      <i class="fas fa-table mr-1"></i>
      Entry Form
    </div>

    <div class="rowdate">
      <div class="col-md-4 order-md-2" style="margin-top: 1em; margin-bottom: 1em;">
        <div class="card border-info mb-3" style="max-width: 20rem;">
          <div class="card-header">Info</div>
          <div class="card-body text-info">
            <h5 class="card-title">Pipeline Information</h5>
            <p class="card-text">We can manually store information to the database coming from the pipeline file we
              receive from the ops
              team here. The hours can be taken from the PIF information as well. <br/><em><u>Please note that the fields here are required.</u></em>
            </p>
          </div>
        </div>
      </div>
  
      <div class="col-md-8 order-md-1" style="margin-top: 1em; margin-bottom: 1em;">
        <form action="{% url 'hcbcapacity:enter-info' %}" class="needs-validation" method="POST">
          {%csrf_token%}
          
          <div>{{form.project_key}}</div>
          <div class="col-md-12 mb-3">
            <label for="prorject_type">Project Type</label>
            {{form.project_type}}
            <div class="invalid-feedback">
              Project Type is required.
            </div>
          </div>
          <div class="col-md-12 mb-3">
            <label for="contract_type">Contract Type</label>
            {{form.contract_type}}
            
            <div class="invalid-feedback">
              Contract type is required.
            </div>
          </div>
          <div class="col-md-12 mb-3">
            <label for="sub_region">Sub Region Type</label>
            {{form.sub_region}}            
            <div class="invalid-feedback">
              sub region is required.
            </div>
          </div>
          <div class="col-md-12 mb-3">
            <label for="summary">Project Name(Summary)</label>
            <div class="input-group">
              {{form.summary}}
              <div class="input-group-append">
                <div class="input-group-text">
                  <i class="fas fa-edit"></i>
                </div> 
              </div>
            </div>

          
            <div class="invalid-feedback">
              {{form.summary.errors}}
            </div>
          </div>
          <span class="rowdate" style="visibility: hidden; width: 0px; height: 0px;">
            {{form.created}}
          </span>
          <span class="col-md-12" style="visibility: hidden; margin:0px; padding: 0px; width: 0px; height: 0px;">
            {{form.proj_status}}
          </span>
          <div class="rowdate">
            <div class="col-md-12 mb-3">
              <label for="SurveySetupStart">Survey Setup Start Date</label>
              <div class="input-group">
                  {{form.survey_setup_start_date}}
                  <div class="input-group-append">
                    <div class="input-group-text">
                      <i class="fas fa-calendar"></i>
                    </div> 
                  </div>
                  
              </div>
              
               
              
            
              <div class="invalid-feedback">
                Survey Setup Start Date is required.
              </div>
            </div>            
          </div>
          <div class="rowdate">
            <div class="col-md-6 mb-3">
              <label for="AdminStart">Admin Start Date</label>
              <div class="input-group">
                {{form.admin_start}}
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="fas fa-calendar"></i>
                  </div> 
                </div>
              </div>
             
              <div class="invalid-feedback">
                Admin Start Date is required.
              </div>
            </div>
            <div class="col-md-6 mb-3">
              <label for="lastName">Admin End Date</label>
              <div class="input-group">
                {{form.admin_end}}
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="fas fa-calendar"></i>
                  </div> 
                </div>
              </div>
             
              <div class="invalid-feedback">
                Admin End Date is required.
              </div>
            </div>
          </div>
          <div class="rowdate">
            <div class="col-md-12 mb-3">
              <label for="EESSetupStart">EES Setup Start Date</label>
              <div class="input-group">
                {{form.ees_start_date}}
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="fas fa-calendar"></i>
                  </div> 
                </div>
                
              </div>
              
              <div class="invalid-feedback">
                EES Setup Start Date is required.
              </div>
            </div>
            <div class="col-md-12 mb-3">
              <label for="EESSubmissionDate">EES Setup Submission Date</label>
              <div class="input-group">
                {{form.ees_submission_end_date}}
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="fas fa-calendar"></i>
                  </div> 
                </div>
              </div>
            
              <div class="invalid-feedback">
                EES Submission Date is required.
              </div>
            </div>
            <div class="col-md-12 mb-3">
              <label for="EESFirstReleaseDate">EES First Results Release Date</label>
              <div class="input-group">
                {{form.ees_first_results_release_date}}
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="fas fa-calendar"></i>
                  </div> 
                </div>
              </div>
            
              <div class="invalid-feedback">
                
                EES First Results Release Date is required.
              </div>
            </div>             
          </div>
          <div class="col-md-12 mb-3">
            <label for="DaName">Delivery Analyst</label>
            {{form.delivery_analyst}}
            <div class="invalid-feedback">
              Delivery Analyst name is required.
            </div>
          </div>     

          <div class="rowdate">
            <div class="col-md-12 mb-3">
              <label for="DaHours">DA Hours</label>
              <div class="input-group">
                {{form.da_hours}}
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="fas fa-keyboard"></i>
                  </div> 
                </div>
              </div>
             
              <div class="invalid-feedback">
                DA Hours is required.
              </div>
            </div>
            
          </div>

          <hr class="mb-4">
        
          <button class="btn btn-primary btn-lg btn-block" type="submit">Submit Information</button>
          

        </form>
      </div>
    </div>
  </div>

</div>

<script>

  $("#id_admin_start").datepicker({
    dateFormat: 'yy-mm-dd',
    showOptions: { direction: "down" }
  });

  $("#id_admin_end").datepicker({
    dateFormat: 'yy-mm-dd',
    showOptions: { direction: "down" }
  });

  $("#id_survey_setup_start_date").datepicker({
    dateFormat: 'yy-mm-dd',
    showOptions: { direction: "down" }
  });

  $("#id_ees_start_date").datepicker({
    dateFormat: 'yy-mm-dd',
    showOptions: { direction: "down" }
  });

  $("#id_ees_submission_end_date").datepicker({
    dateFormat: 'yy-mm-dd',
    showOptions: { direction: "down" }
  });

  $("#id_ees_first_results_release_date").datepicker({
    dateFormat: 'yy-mm-dd',
    showOptions: { direction: "down" }
  });
</script>

{%endblock content%}

hcbresourcesite/hcbcapacity/templates/hcbcapacity/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title%}
{% block nav-style %}mkt-nav{% endblock nav-style%}

{% block content %}   

    <div class="container-fluid">     
        
        <h1 class="mt-4">Project List</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>
        
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                DataTable Example
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Key</th>
                                <th>Project Name</th>
                                <th>Status</th>
                                <th>Complexity</th>
                                <th>Admin Start Date</th>
                                <th>Admin End Date</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Key</th>
                                <th>Project Name</th>
                                <th>Status</th>
                                <th>Complexity</th>
                                <th>Admin Start Date</th>
                                <th>Admin End Date</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            {% if latest_project_list %}   
                            {% for projectlist in latest_project_list %}
                            <tr>
                                <td><a href='http://jira.ehr.com/browse/{{projectlist.project_key}}'>{{projectlist.project_key}}</a></td>
                                <td>{{projectlist.summary}}</td>
                                <td>{{projectlist.proj_status}}</td>
                                <td>{{projectlist.complexity}}</td>
                                <td>{{projectlist.admin_start.date}}</td>
                                <td>{{projectlist.admin_end.date}}</td>
                                
                            </tr>
                            {% endfor %}
                            {% else %}
                                <p>no data found</p>
                            {% endif %}
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

hcbresourcesite/hcbcapacity/templates/hcbcapacity/projwda.html
{% extends 'base.html' %}
{% block title %}Project List without DA{% endblock title%}
{% block nav-style %}mkt-nav{% endblock nav-style%}

{% block content %}   

    <div class="container-fluid">     
        
        <h1 class="mt-4">Project List</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Filtered DA projects</li>
        </ol>
        
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Projects of selected Delivery Analyst
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Key</th>                                
                                <th>Delivery Analyst</th>
                                <th>Project Name</th>
                                <th>Status</th>
                                <th>Complexity</th>                                
                                <th>DA Hours Required</th>
                                <th>Admin Start Date</th>
                                <th>EES First Results Release Date</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Key</th>                                
                                <th>Delivery Analyst</th>
                                <th>Project Name</th>
                                <th>Status</th>
                                <th>Complexity</th>                                
                                <th>DA Hours Required</th>
                                <th>Admin Start Date</th>
                                <th>EES First Results Release Date</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            {% if list_projects_w_da %}   
                            {% for projectlist in list_projects_w_da %}
                            <tr>
                                <td><a href='http://jira.ehr.com/browse/{{projectlist.project_key}}'>{{projectlist.project_key}}</a></td>
                               
                                <td>{{projectlist.delivery_analyst}}</td>
                                <td>{{projectlist.summary}}</td>
                                <td>{{projectlist.proj_status}}</td>
                                <td>{{projectlist.complexity}}</td>                               
                                <td>{{projectlist.da_hours}}</td>
                                <td>{{projectlist.admin_start.date}}</td>
                                <td>{{projectlist.ees_first_results_release_date.date}}</td>
                                
                            </tr>
                            {% endfor %}
                            {% else %}
                                <p>no data found</p>
                            {% endif %}
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}